### ISSUE TITLE
vid2seq 分支d63da0d7971fc9caa5d4876545e055063f79afd6  commit gpu 逻辑错误

### ISSUE THREAD

**Issue by zdx3578** [createamind/vid2vid#10]
commit d63da0d7971fc9caa5d4876545e055063f79afd6
Merge: 54a676d a7884f0
Author: SRTjiawei <jeven.z@aliyun.com>
Date:   Tue Jan 2 23:05:31 2018 +0800e

error:

zmq.error.ZMQError: Address already in use
Traceback (most recent call last):
  File "train.py", line 210, in <module>
    g_mse_loss = model.optimize_parameters()
  File "/home/sdc/Projects/video4-pytorch-CycleGAN-and-pix2pix/models/vid2seq_model.py", line 277, in optimize_parameters
    self.backward_D()
  File "/home/sdc/Projects/video4-pytorch-CycleGAN-and-pix2pix/models/vid2seq_model.py", line 167, in backward_D
    pred_fake = self.netD_vid(fake_AB_.detach())
  File "/home/sdc/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sdc/Projects/video4-pytorch-CycleGAN-and-pix2pix/models/networks.py", line 486, in forward
    return self.model(input)
  File "/home/sdc/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sdc/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/sdc/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sdc/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 350, in forward
    self.padding, self.dilation, self.groups)
  File "/home/sdc/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 116, in conv3d
    return f(input, weight, bias)
RuntimeError: tensors are on different GPUs

gpu判断错误，走cpu处理逻辑了

回退到

commit d63da0d7971fc9caa5d4876545e055063f79afd6
Merge: 54a676d a7884f0
Author: SRTjiawei <jeven.z@aliyun.com>
Date:   Tue Jan 2 23:05:31 2018 +0800

可以正常运行

**Comment by zdx3578** [comment]
新函数参数传递没修改就导致传参数错误了吧

**Comment by zdx3578** [comment]
新加的参数放最后，不影响之前的参数对应关系
